# Generated by Django 4.0.4 on 2022-07-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0011_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postapp.profile'),
        ),
    ]
