# Generated by Django 4.0.4 on 2022-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0013_comment_writer_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writer_school',
            new_name='writer_profile',
        ),
    ]
