# Generated by Django 4.0.4 on 2022-07-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0014_rename_writer_school_comment_writer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_school',
            new_name='author_profile',
        ),
    ]
