# Generated by Django 4.0.4 on 2022-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0015_rename_author_school_post_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='postapp.post'),
        ),
    ]
