# Generated by Django 4.0.4 on 2022-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0019_remove_post_like_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to='postapp.profile'),
        ),
    ]
