# Generated by Django 4.0.4 on 2022-07-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0022_remove_post_like_users_post_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_comment',
            field=models.ManyToManyField(blank=True, related_name='like_users_comment', to='postapp.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='postapp.post'),
        ),
    ]
