# Generated by Django 4.0.4 on 2022-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0023_comment_like_count_profile_like_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_comment',
            field=models.ManyToManyField(blank=True, related_name='like_users_comment', to='postapp.comment'),
        ),
    ]
